Bugfix: CI Fixes (#239)
* ci warning fixes and bug fixes

* appears new version of deepdiff can't process some of the objects, they were identical when I was viewing them, this will remove the unprocessed differences and throw a warning with those values instead

* fixes test_evaluation.py::test_gof_perfect[gof-simulation-CHRTOUT-lambda_identity-None-xr] failure because xarray can't be converted to numpy array

* ci fix to test_evaluation.py::test_crps_brier_basic[crps-pd], for 'TypeError: mean() got an unexpected keyword argument 'level'' because observed was a pandas series and not a pandas dataframe

* ci fix to test_evaluation.py::test_crps_brier_basic[crps-pd], for 'TypeError: mean() got an unexpected keyword argument 'level'' because observed was a pandas series and not a pandas dataframe

* ci fix to test_evaluation.py::test_crps_brier_basic[brier-pd], for 'TypeError: mean() got an unexpected keyword argument 'level'' because observed was a pandas series and not a pandas dataframe

* ci bugfix: fix to test_evaluation.py test groups test_contingency_known_data and test_contingency_missing_columns

* ci bugfix: better checking of unprocessed deepdiffs, fixed ensemble tests

* ci cleanup: switching to the new method for checking unprocessed diffs

* bumping versions so ci tests pass

* ci micromamba: updating depricated behavior and environment-file requirements

* ci fix: not sure if this is the correct way to fix this but it does fix the test test_collection::test_collect_missing_ens_cycle[missing_ens_cycle-CHRTOUT_DOMAIN1]

* micromamba can't install nccmp for Windows. This lets it do it for Ubuntu and MacOS and uses for Windows it gets zip file and uses binary

* ci windows runner fix: install nccmp manually for windows

* ci testing: testing only one version of python so runner doesn't time out

* commenting out _compose_dirs unexpected diff warning so that it returns an error. Checking how it will effect the CI

* Updating requirements and setup files so that they build and run tests with Python 3.7